Deps: Update faithfuls <easy-as-pypi>
- Source: easy-as-pypi @ 7ee39719fb4a [1.1.14a2~3]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/doblabs/easy-as-pypi/blob/release/bin/update-faithful

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -54,6 +54,7 @@ __UPDEPS__CPYST__="
   UPDEPS_CASCADE_UPDATEDEPS=skip \
   UPDEPS_CASCADE_VERSIONING=skip \
   UPDEPS_INCLUDE_PRERELEASE=false \
+  UPDEPS_SKIP_PR=false \
     ./.github/bin/update-poetry
 "
 
@@ -229,10 +230,12 @@ update_poetry_update () {
   local NEW_PR_URL=""
 
   if ${has_changes}; then
-    push_branch "${branch_name}" "${remote_name}"
+    if ! ${UPDEPS_SKIP_PR:-false}; then
+      push_branch "${branch_name}" "${remote_name}"
 
-    # Set NEW_PR_URL
-    gh_pr_create_and_auto_merge_when_checks_finish
+      # Set NEW_PR_URL
+      gh_pr_create_and_auto_merge_when_checks_finish
+    fi
 
     resume_old_branch_and_cleanup "${branch_name}"
   else
@@ -342,10 +345,12 @@ poetry_update_lock_normal () {
       print_prog "full... "
 
       poetry update --lock >> "${POETRY_OUTPUT_DUMP}"
+    elif [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "skip" ]; then
+      print_prog "skip "
     else
-      # Note that UPDEPS_CASCADE_UPDATEDEPS cannot be 'skip', because
-      # caller precludes calling this script otherwise.
-      >&2 echo "GAFFE: Impossible path"
+      >&2 echo "ERROR: Unrecognized UPDEPS_CASCADE_UPDATEDEPS value:" \
+        "‘${UPDEPS_CASCADE_UPDATEDEPS}’"
+      >&2 echo "- Hint: Try one of: 'ours', 'full', or 'skip'"
 
       # D_b_C: This execution is kaput, by the laws of Design by Contract.
       exit_1
@@ -420,7 +425,10 @@ generate_branch_name () {
 prepare_branch () {
   local branch_name="$1"
 
-  if [ "$(git_branch_name)" = "${branch_name}" ]; then
+  local curr_branch
+  curr_branch="$(git_branch_name)"
+
+  if [ "${curr_branch}" = "${branch_name}" ]; then
     # Assumed previously called and all setup.
 
     return 0
@@ -428,7 +436,9 @@ prepare_branch () {
 
   # ***
 
-  local scoped_head="HEAD"
+  _ORIGINAL_BRANCH="${curr_branch}"
+
+  local scoped_head
   scoped_head="$(print_scoped_head ".")"
 
   print_prog "git checkout -b ${branch_name} ${scoped_head}\n"
@@ -447,7 +457,18 @@ prepare_branch () {
 resume_old_branch_and_cleanup () {
   local branch_name="$1"
 
-  git checkout -q -
+  # Note that `git checkout -` fails if `gh pr merge` deleted the PR branch.
+  #   $ git checkout -
+  #   error: pathspec '-' did not match any file(s) known to git
+  # So use branch name instead.
+
+  if [ -n "${_ORIGINAL_BRANCH}" ]; then
+    print_prog "git checkout -q ${_ORIGINAL_BRANCH}\n"
+
+    git checkout -q "${_ORIGINAL_BRANCH}"
+
+    _ORIGINAL_BRANCH=""
+  fi
 
   _CHANGED_BRANCH=""
 
@@ -458,10 +479,20 @@ resume_old_branch_and_cleanup () {
   #   - REFER:
   # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
   if ! ${CI:-false}; then
-    # Ignore stderr message that -q doesn't inhibit:
-    #   warning: deleting branch 'foo' that has been merged to
-    #            'refs/remotes/origin/foo', but not yet merged to HEAD.
-    git branch -q -D "${branch_name}" 2> /dev/null
+    if ! ${UPDEPS_SKIP_PR:-false}; then
+      print_prog "git branch -q -D ${branch_name}\n"
+      # Ignore stderr message that -q doesn't inhibit:
+      #   warning: deleting branch 'foo' that has been merged to
+      #            'refs/remotes/origin/foo', but not yet merged to HEAD.
+      # - Note that the earlier `gh pr merge` may have deleted the local
+      #   branch already, so avoid tripping errexit.
+      git branch -q -D "${branch_name}" 2> /dev/null || true
+    else
+      echo "You opted to not use a PR, so you'll need to merge changes yourself:"
+      echo
+      echo "  git rebase ${branch_name}"
+      echo "  git branch -d ${branch_name}"
+    fi
   fi
 }
 
@@ -689,7 +720,7 @@ gh_pr_create_and_auto_merge_when_checks_finish () {
     print_prog
   fi
 
-  print_prog "New PR\n  ${NEW_PR_URL}\n"
+  print_prog "New PR\n  ${NEW_PR_URL}\n\n"
 }
 
 gh_label_create_poetry_lock_label () {
@@ -819,8 +850,12 @@ gh_pr_set_auto_merge_delete_rebase () {
 
   print_prog "gh pr merge \"${pr_ref}\" --auto --delete-branch --rebase\n"
 
+  # SAVVY/2023-12-18: If there are no branch protection rules and
+  # mandatory checks, this'll actually merge immediately, and it'll
+  # delete the local branch. (And that's why `git checkout -` later
+  # fails.)
   GH_TOKEN=${USER_TOKEN} \
-  gh pr merge "${pr_ref}" --auto --delete-branch --rebase
+  gh pr merge "${pr_ref}" --auto --delete-branch --rebase 1>&2
 }
 
 # CXREF: https://github.com/doblabs/easy-as-pypi/settings/actions
@@ -844,7 +879,7 @@ gh_pr_approve () {
   # branch protection rule.
 
   GH_TOKEN=${GBOT_TOKEN} \
-  gh pr review "${pr_ref}" --approve --body "LGTM!" \
+  gh pr review "${pr_ref}" --approve --body "LGTM!" 1>&2 \
     || true
 }
 
@@ -1041,6 +1076,7 @@ exit_1 () { _NORMAL_EXIT=true; exit 1; }
 exit_0 () { _NORMAL_EXIT=true; exit 0; }
 
 _CHANGED_BRANCH=""
+_ORIGINAL_BRANCH=""
 
 exit_cleanup () {
   if [ -n "${_CHANGED_BRANCH}" ]; then
